[project]
name = "log-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "apache-log-parser>=1.7.0",
    "js-jquery-tablesorter>=2.0.5",
    "pip>=25.2",
    "pyparsing>=3.2.5",
    "requests>=2.32.5",
]
