name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install .[test]

      - name: Run unit tests with coverage
        run: |
          source venv/bin/activate
          pytest src/tests/

  ruff_check:
    name: Ruff Check
    runs-on: ubuntu-latest
    needs: testing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Ruff check
        run: |
          docker run --rm -v $PWD:/app -w /app ghcr.io/astral-sh/ruff:0.9.1-alpine ruff check .

  ruff_format:
    name: Ruff Format
    runs-on: ubuntu-latest
    needs: ruff_check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Ruff format
        run: |
          docker run --rm -v $PWD:/app -w /app ghcr.io/astral-sh/ruff:0.9.1-alpine ruff format --check .